// Code generated by mockery v1.0.0. DO NOT EDIT.

// This comment works around https://github.com/vektra/mockery/issues/155

package unix

import mock "github.com/stretchr/testify/mock"
import user "github.com/opencontainers/runc/libcontainer/user"

// mockFakeUserFinder is an autogenerated mock type for the fakeUserFinder type
type mockFakeUserFinder struct {
	mock.Mock
}

// Find provides a mock function with given fields: username
func (_m *mockFakeUserFinder) Find(username string) (user.User, error) {
	ret := _m.Called(username)

	var r0 user.User
	if rf, ok := ret.Get(0).(func(string) user.User); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
