// Code generated by mockery v1.0.0. DO NOT EDIT.

// This comment works around https://github.com/vektra/mockery/issues/155

package unix

import mock "github.com/stretchr/testify/mock"
import syscall "syscall"

// mockFakeProcessKiller is an autogenerated mock type for the fakeProcessKiller type
type mockFakeProcessKiller struct {
	mock.Mock
}

// Kill provides a mock function with given fields: pid, signal
func (_m *mockFakeProcessKiller) Kill(pid int, signal syscall.Signal) error {
	ret := _m.Called(pid, signal)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, syscall.Signal) error); ok {
		r0 = rf(pid, signal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
