// Code generated by mockery v1.1.0. DO NOT EDIT.

package runnershell

import mock "github.com/stretchr/testify/mock"

// MockFunction is an autogenerated mock type for the Function type
type MockFunction struct {
	mock.Mock
}

// execute provides a mock function with given fields: _a0
func (_m *MockFunction) execute(_a0 *Options) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Options) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
