// Code generated by mockery v1.0.0. DO NOT EDIT.

// This comment works around https://github.com/vektra/mockery/issues/155

package windows

import mock "github.com/stretchr/testify/mock"

// mockFakeProcessKiller is an autogenerated mock type for the fakeProcessKiller type
type mockFakeProcessKiller struct {
	mock.Mock
}

// Kill provides a mock function with given fields: pid
func (_m *mockFakeProcessKiller) Kill(pid int) {
	_m.Called(pid)
}
