// Code generated by mockery v1.0.0. DO NOT EDIT.

package client

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// IsServerReady provides a mock function with given fields:
func (_m *MockClient) IsServerReady() VaultServerReadyResp {
	ret := _m.Called()

	var r0 VaultServerReadyResp
	if rf, ok := ret.Get(0).(func() VaultServerReadyResp); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(VaultServerReadyResp)
	}

	return r0
}

// SetToken provides a mock function with given fields: token
func (_m *MockClient) SetToken(token string) {
	_m.Called(token)
}
