// Code generated by mockery v1.1.0. DO NOT EDIT.

package debug

import (
	http "net/http"

	common "gitlab.com/gitlab-org/gitlab-runner/common"

	mock "github.com/stretchr/testify/mock"
)

// MockListJobsHandler is an autogenerated mock type for the ListJobsHandler type
type MockListJobsHandler struct {
	mock.Mock
}

// LegacyListJobsHandler provides a mock function with given fields: w, r
func (_m *MockListJobsHandler) LegacyListJobsHandler(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ListJobs provides a mock function with given fields:
func (_m *MockListJobsHandler) ListJobs() []*common.Build {
	ret := _m.Called()

	var r0 []*common.Build
	if rf, ok := ret.Get(0).(func() []*common.Build); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*common.Build)
		}
	}

	return r0
}
