FROM registry.access.redhat.com/ubi8/ubi:8.1

RUN dnf --disableplugin=subscription-manager install -yb --nodocs \
    git \
    hostname \
    perl

# TODO: COPY ./git-lfs /usr/local/bin/git-lfs
COPY ./scripts/gitlab-runner-build /usr/local/bin/gitlab-runner-build
COPY ./binaries/gitlab-runner-helper /usr/local/bin/gitlab-runner-helper

RUN chmod +x /usr/local/bin/gitlab-runner-helper

# RUN git lfs install --skip-repo

USER 1001

CMD ["sh"]
