FROM registry.access.redhat.com/ubi8/ubi@sha256:f6648a87c8c52099bacd19b112beb3b65407ae6d3441f9b559ba53c4112c57a4

RUN dnf --disableplugin=subscription-manager install -yb --nodocs \
    git \
    hostname \
    perl

# TODO: COPY ./git-lfs /usr/local/bin/git-lfs
COPY ./helpers/gitlab-runner-build /usr/local/bin/gitlab-runner-build
COPY ./binaries/gitlab-runner-helper /usr/local/bin/gitlab-runner-helper

RUN chmod +x /usr/local/bin/gitlab-runner-helper

# RUN git lfs install --skip-repo

USER 1001

CMD ["sh"]