// Code generated by mockery v1.0.0. DO NOT EDIT.

// This comment works around https://github.com/vektra/mockery/issues/155

package process

import mock "github.com/stretchr/testify/mock"

// MockGroup is an autogenerated mock type for the Group type
type MockGroup struct {
	mock.Mock
}

// Kill provides a mock function with given fields:
func (_m *MockGroup) Kill() {
	_m.Called()
}

// Prepare provides a mock function with given fields:
func (_m *MockGroup) Prepare() {
	_m.Called()
}
