// Code generated by mockery v1.0.0. DO NOT EDIT.

package process

import mock "github.com/stretchr/testify/mock"
import os "os"

// MockKillWaiter is an autogenerated mock type for the KillWaiter type
type MockKillWaiter struct {
	mock.Mock
}

// KillAndWait provides a mock function with given fields: process, waitCh
func (_m *MockKillWaiter) KillAndWait(process *os.Process, waitCh chan error) error {
	ret := _m.Called(process, waitCh)

	var r0 error
	if rf, ok := ret.Get(0).(func(*os.Process, chan error) error); ok {
		r0 = rf(process, waitCh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
