// Code generated by mockery v1.0.0

// This comment works around https://github.com/vektra/mockery/issues/155

package network

import mock "github.com/stretchr/testify/mock"

// MockRequestCredentials is an autogenerated mock type for the RequestCredentials type
type MockRequestCredentials struct {
	mock.Mock
}

// GetTLSCAFile provides a mock function with given fields:
func (_m *MockRequestCredentials) GetTLSCAFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTLSCertFile provides a mock function with given fields:
func (_m *MockRequestCredentials) GetTLSCertFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTLSKeyFile provides a mock function with given fields:
func (_m *MockRequestCredentials) GetTLSKeyFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetToken provides a mock function with given fields:
func (_m *MockRequestCredentials) GetToken() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetURL provides a mock function with given fields:
func (_m *MockRequestCredentials) GetURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
