#!/usr/bin/env bash

set -eo pipefail

downloadURL="https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VERSION}/git-lfs-linux-amd64-v${GIT_LFS_VERSION}.tar.gz"

wget "${downloadURL}" -O /tmp/git-lfs.tar.gz

echo "${GIT_LFS_256_CHECKSUM}  /tmp/git-lfs.tar.gz" > /tmp/checksums
sha256sum -c /tmp/checksums

tar -xzf /tmp/git-lfs.tar.gz -C /tmp
mkdir -p /build/usr/local/bin
mv /tmp/git-lfs /build/usr/local/bin
chmod +x /build/usr/local/bin/git-lfs
