#!/usr/bin/env bash

set -eo pipefail

apt-get update -yq
apt-get install -yq --no-install-recommends \
                bzip2 locales make xz-utils \
                ruby ruby-dev python-pip \
                dpkg-sig createrepo rpm \
                zip libffi-dev jq
rm -rf /var/lib/apt/lists/*

echo "en_US UTF-8" > /etc/locale.gen
locale-gen en_US.UTF-8

cd /tmp/build
make deps package-deps packagecloud-deps
cd /tmp
rm -rf /tmp/build /usr/share/doc

git-lfs install --skip-repo

go get -u github.com/jstemmer/go-junit-report

# Install Powershell Core
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
apt-get update
apt-get install -y "powershell=${PWSH_VERSION}.debian.10"
rm -rf /var/lib/apt/lists/*
pwsh --version