// Code generated by mockery v1.0.0. DO NOT EDIT.

package secret

import config "gitlab.com/gitlab-org/gitlab-runner/vault/config"
import mock "github.com/stretchr/testify/mock"

// MockBuilder is an autogenerated mock type for the Builder type
type MockBuilder struct {
	mock.Mock
}

// BuildSecret provides a mock function with given fields: secretSpec, data
func (_m *MockBuilder) BuildSecret(secretSpec *config.VaultSecretKey, data interface{}) error {
	ret := _m.Called(secretSpec, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.VaultSecretKey, interface{}) error); ok {
		r0 = rf(secretSpec, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
