// Code generated by mockery v1.1.0. DO NOT EDIT.

package probe

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockProber is an autogenerated mock type for the Prober type
type MockProber struct {
	mock.Mock
}

// Probe provides a mock function with given fields: ctx, timeout
func (_m *MockProber) Probe(ctx context.Context, timeout time.Duration) error {
	ret := _m.Called(ctx, timeout)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) error); ok {
		r0 = rf(ctx, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *MockProber) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
