// Code generated by mockery v1.0.0. DO NOT EDIT.

package referees

import mock "github.com/stretchr/testify/mock"

// MockRefereeExecutor is an autogenerated mock type for the RefereeExecutor type
type MockRefereeExecutor struct {
	mock.Mock
}

// GetHostname provides a mock function with given fields:
func (_m *MockRefereeExecutor) GetHostname() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
