// Code generated by mockery v1.0.0. DO NOT EDIT.

package vault

import config "gitlab.com/gitlab-org/gitlab-runner/vault/config"
import mock "github.com/stretchr/testify/mock"

// MockVault is an autogenerated mock type for the Vault type
type MockVault struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: auth
func (_m *MockVault) Authenticate(auth config.VaultAuth) error {
	ret := _m.Called(auth)

	var r0 error
	if rf, ok := ret.Get(0).(func(config.VaultAuth) error); ok {
		r0 = rf(auth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Connect provides a mock function with given fields: server
func (_m *MockVault) Connect(server config.VaultServer) error {
	ret := _m.Called(server)

	var r0 error
	if rf, ok := ret.Get(0).(func(config.VaultServer) error); ok {
		r0 = rf(server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadSecrets provides a mock function with given fields: secrets
func (_m *MockVault) ReadSecrets(secrets config.VaultSecrets) error {
	ret := _m.Called(secrets)

	var r0 error
	if rf, ok := ret.Get(0).(func(config.VaultSecrets) error); ok {
		r0 = rf(secrets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
