// Code generated by mockery v1.0.0. DO NOT EDIT.

package vault

import client "gitlab.com/gitlab-org/gitlab-runner/vault/client"
import config "gitlab.com/gitlab-org/gitlab-runner/vault/config"
import mock "github.com/stretchr/testify/mock"

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: cli, authConfig
func (_m *MockAuthenticator) Authenticate(cli client.Client, authConfig config.VaultAuth) (client.TokenInfo, error) {
	ret := _m.Called(cli, authConfig)

	var r0 client.TokenInfo
	if rf, ok := ret.Get(0).(func(client.Client, config.VaultAuth) client.TokenInfo); ok {
		r0 = rf(cli, authConfig)
	} else {
		r0 = ret.Get(0).(client.TokenInfo)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(client.Client, config.VaultAuth) error); ok {
		r1 = rf(cli, authConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
