// Code generated by mockery v1.0.0. DO NOT EDIT.

package vault

import client "gitlab.com/gitlab-org/gitlab-runner/vault/client"
import config "gitlab.com/gitlab-org/gitlab-runner/vault/config"
import mock "github.com/stretchr/testify/mock"
import secret "gitlab.com/gitlab-org/gitlab-runner/vault/secret"

// MockSecretReader is an autogenerated mock type for the SecretReader type
type MockSecretReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: cli, builder, path, secretSpec
func (_m *MockSecretReader) Read(cli client.Client, builder secret.Builder, path string, secretSpec *config.VaultSecret) error {
	ret := _m.Called(cli, builder, path, secretSpec)

	var r0 error
	if rf, ok := ret.Get(0).(func(client.Client, secret.Builder, string, *config.VaultSecret) error); ok {
		r0 = rf(cli, builder, path, secretSpec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
