// Code generated by mockery v1.1.0. DO NOT EDIT.

package common

import mock "github.com/stretchr/testify/mock"

// MockCacheCredentialsProvider is an autogenerated mock type for the CacheCredentialsProvider type
type MockCacheCredentialsProvider struct {
	mock.Mock
}

// GetCredentials provides a mock function with given fields:
func (_m *MockCacheCredentialsProvider) GetCredentials() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}
