#!/usr/bin/env bash

set -eo pipefail

TESTFLAGS=${TESTFLAGS:-"-cover"}
PARALLEL_TESTS_LIMIT=${PARALLEL_TESTS_LIMIT:-8}

CI_NODE_TOTAL=${CI_NODE_TOTAL:-1}
CI_NODE_INDEX=${CI_NODE_INDEX:-1}

testsDefinitions="testsdefinitions-$CI_NODE_INDEX"

output="regular"
coverMode="count"

if [[ ${TESTFLAGS} = *"-race"* ]]; then
    output="race"
    coverMode="atomic"
fi

printMessage() {
  echo -e "\\033[1m${*}\\033[0m"
}

joinBy() {
    local IFS="${1}"
    shift
    echo "${*}"
}

executeTestCommand() {
    local pkg=${1}
    local index=${2}
    local runTestsList=${3}

    local options=""

    local pkgSlug
    pkgSlug=$(echo "${pkg}" | tr "/" "-")

    local type
    if [[ ${TESTFLAGS} = *'tags=integration'* ]]; then
        type="integration"
    else
        type="unit"
    fi

    if [[ ${TESTFLAGS} = *'-cover'* ]]; then
        mkdir -p ".cover/${type}"
        mkdir -p ".testoutput/${type}"

        printMessage "\\n\\n--- Starting part ${index} of go ${type} tests of '${pkg}' package with coverprofile in '${coverMode}' mode:\\n"

        local profileFile=".cover/${type}/${index}.${coverMode}.cover.txt"
        options="-covermode=${coverMode} -coverprofile=${profileFile} -coverpkg=${MAIN_PACKAGE}/..."
    else
        echo "Starting go ${type} test"
    fi

    local testOutputFile=".testoutput/${type}/${index}.${output}.output.txt"

    local exitCode=0
    # shellcheck disable=SC2086
    go test ${options} ${TESTFLAGS} -ldflags "${GO_LDFLAGS}" -v -run "${runTestsList}" ${pkg} 2>&1 | tee "${testOutputFile}" || exitCode=1

    return ${exitCode}
}

executeTestPart() {
    rm -rf .cover/ .testoutput/

    numberOfDefinitions=$(< "${testsDefinitions}" wc -l)

    printMessage "Number of definitions: ${numberOfDefinitions}"
    printMessage "Suite size: ${CI_NODE_TOTAL}"
    printMessage "Suite index: ${CI_NODE_INDEX}"

    local exitCode=0
    while read -r tests pkg; do
        executeTestCommand "${pkg}" "${CI_NODE_INDEX}" "${tests}" || exitCode=1
    done < <(cat "${testsDefinitions}")

    exit ${exitCode}
}

computeCoverageReport() {
    local reportDirectory="out/coverage"
    local sourceFile="${reportDirectory}/coverprofile.${output}.source.txt"
    local htmlReportFile="${reportDirectory}/coverprofile.${output}.html"
    local textReportFile="${reportDirectory}/coverprofile.${output}.txt"

    mkdir -p "${reportDirectory}"

    echo "mode: ${coverMode}" > ${sourceFile}
    grep -h -v -E -e "^mode:" -e "\/mock_[^\.]+\.go" .cover/*/*.${coverMode}.cover.txt >> ${sourceFile}

    printMessage "Generating HTML coverage report"
    go tool cover -o ${htmlReportFile} -html=${sourceFile}
    printMessage "Generating TXT coverage report"
    go tool cover -o ${textReportFile} -func=${sourceFile}

    printMessage "General coverage percentage:"
    local total
    total=$(grep "total" "${textReportFile}" || echo "")

    if [[ -n "${total}" ]]; then
        echo "${output} ${total}"
    fi
}

computeJUnitReport() {
    local reportDirectory="out/junit"
    local concatenatedOutputFile="/tmp/test-output.txt"

    mkdir -p "${reportDirectory}"

    cat .testoutput/*/*.${output}.output.txt > "${concatenatedOutputFile}"

    go-junit-report < "${concatenatedOutputFile}" > "${reportDirectory}/report.xml"
}

case "$1" in
    prepare)
        go run scripts/parallel-tests/main.go ./...
        ;;
    execute)
        executeTestPart
        ;;
    coverage)
        computeCoverageReport
        ;;
    junit)
        computeJUnitReport
        ;;
esac
