#!/bin/bash

set -eo pipefail

echo "Fixing FD-0 bug..."
eval $(go env)

# When the patch has already been applied patch can return a non 0 exit code
# This can cause problems in CI if the patch has already been applied but the
# .patched_go_env file doesn't exist for the make check
patch -p1 -N -d "$GOROOT" <scripts/exec_unix.go.patch || true
