#!/usr/bin/env bash

set -eo pipefail

IS_LATEST=${IS_LATEST:-}

ref_tag=${CI_COMMIT_TAG}
if [[ -z "${ref_tag}" ]]; then
    ref_tag=${CI_COMMIT_REF_SLUG:-master}
fi

if [[ "${ref_tag}" = "master" ]]; then
    ref_tag=bleeding
fi

REVISION=${REVISION:-}
if [[ -z "${REVISION}" ]]; then
  REVISION=$(git rev-parse --short=8 HEAD || echo "unknown")
fi

_docker() {
    docker ${@}
}

build() {
    local tag=${1}
    local directory=${2}
    local dockerfile=${3:-Dockerfile}

    echo -e "\033[1mBuilding image: \033[32m${1}\033[0m"
    _docker build \
        --no-cache \
        --build-arg DOCKER_MACHINE_VERSION="${DOCKER_MACHINE_VERSION}" \
        --build-arg DUMB_INIT_VERSION="${DUMB_INIT_VERSION}" \
        --build-arg GIT_LFS_VERSION="${GIT_LFS_VERSION}" \
        -t "${tag}" \
        -f "${directory}/${dockerfile}" \
        "${directory}"
}

import() {
    echo -e "\033[1mImporting image: \033[32m${2}\033[0m"
    _docker import "${1}" "${2}"
}

tag() {
    echo -e "\033[1mTagging image: \033[32m${2}\033[0m"
    _docker tag "${1}" "${2}"
}

tag_latest() {
    if [[ -z "${IS_LATEST}" ]]; then
        return
    fi

    tag "${@}"
}

push() {
    echo -e "\033[1mPushing image: \033[32m${1}\033[0m"
    _docker push "${1}"
}

push_latest() {
    if [[ -z "${IS_LATEST}" ]]; then
        return
    fi

    push "${@}"
}

release_docker_helper_images() {
    helper_image_x86_64="gitlab/gitlab-runner-helper:x86_64-${REVISION}"
    helper_image_x86_64_latest="gitlab/gitlab-runner-helper:x86_64-latest"
    helper_image_arm="gitlab/gitlab-runner-helper:arm-${REVISION}"
    helper_image_arm_latest="gitlab/gitlab-runner-helper:arm-latest"
    helper_image_arm64="gitlab/gitlab-runner-helper:arm64-${REVISION}"
    helper_image_arm64_latest="gitlab/gitlab-runner-helper:arm64-latest"

    import out/helper-images/prebuilt-x86_64.tar.xz ${helper_image_x86_64}
    import out/helper-images/prebuilt-arm.tar.xz ${helper_image_arm}
    import out/helper-images/prebuilt-arm64.tar.xz ${helper_image_arm64}

    tag_latest ${helper_image_x86_64} ${helper_image_x86_64_latest}
    tag_latest ${helper_image_arm} ${helper_image_arm_latest}
    tag_latest ${helper_image_arm64} ${helper_image_arm64_latest}


    push ${helper_image_x86_64}
    push ${helper_image_arm}
    push ${helper_image_arm64}

    push_latest ${helper_image_x86_64_latest}
    push_latest ${helper_image_arm_latest}
    push_latest ${helper_image_arm64_latest}
}

login() {
    _docker login --username "${1}" --password "${2}" "${3}"
}

logout() {
    _docker logout "${1}"
}

checksums() {
    local arch=${1:-AMD64}

    eval ch=\$"DOCKER_MACHINE_CHECKSUM_${arch}"
    echo "${ch}  /usr/bin/docker-machine" > dockerfiles/checksums

    eval ch=\$"DUMB_INIT_CHECKSUM_${arch}"
    echo "${ch}  /usr/bin/dumb-init" >> dockerfiles/checksums

    eval ch=\$"GIT_LFS_CHECKSUM_${arch}"
    echo "${ch}  /usr/bin/git-lfs" >> dockerfiles/checksums

    echo "Checksums for ${arch} architecture:"
    cat dockerfiles/checksums

    cp dockerfiles/checksums dockerfiles/alpine
    cp dockerfiles/checksums dockerfiles/ubuntu
}

cp out/deb/gitlab-runner_amd64.deb dockerfiles/ubuntu/
cp out/deb/gitlab-runner_armhf.deb dockerfiles/ubuntu/
cp out/deb/gitlab-runner_arm64.deb dockerfiles/ubuntu/

cp out/binaries/gitlab-runner-linux-amd64 dockerfiles/alpine
cp out/binaries/gitlab-runner-linux-arm dockerfiles/alpine
cp out/binaries/gitlab-runner-linux-arm64 dockerfiles/alpine

checksums
build "gitlab/gitlab-runner:ubuntu-${ref_tag}" dockerfiles/ubuntu
build "gitlab/gitlab-runner:alpine-${ref_tag}" dockerfiles/alpine

checksums ARM
build "gitlab/gitlab-runner:ubuntu-arm-${ref_tag}" dockerfiles/ubuntu Dockerfile.arm
build "gitlab/gitlab-runner:alpine-arm-${ref_tag}" dockerfiles/alpine Dockerfile.arm

checksums ARM64
build "gitlab/gitlab-runner:ubuntu-arm64-${ref_tag}" dockerfiles/ubuntu Dockerfile.arm64
build "gitlab/gitlab-runner:alpine-arm64-${ref_tag}" dockerfiles/alpine Dockerfile.arm64

tag "gitlab/gitlab-runner:ubuntu-${ref_tag}" "gitlab/gitlab-runner:${ref_tag}"
tag "gitlab/gitlab-runner:ubuntu-arm-${ref_tag}" "gitlab/gitlab-runner:arm-${ref_tag}"
tag "gitlab/gitlab-runner:ubuntu-arm64-${ref_tag}" "gitlab/gitlab-runner:arm64-${ref_tag}"

tag_latest "gitlab/gitlab-runner:ubuntu-${ref_tag}" gitlab/gitlab-runner:latest
tag_latest "gitlab/gitlab-runner:ubuntu-arm-${ref_tag}" gitlab/gitlab-runner:arm
tag_latest "gitlab/gitlab-runner:ubuntu-arm64-${ref_tag}" gitlab/gitlab-runner:arm64

tag_latest "gitlab/gitlab-runner:ubuntu-${ref_tag}" gitlab/gitlab-runner:ubuntu
tag_latest "gitlab/gitlab-runner:ubuntu-arm-${ref_tag}" gitlab/gitlab-runner:ubuntu-arm
tag_latest "gitlab/gitlab-runner:ubuntu-arm64-${ref_tag}" gitlab/gitlab-runner:ubuntu-arm64

tag_latest "gitlab/gitlab-runner:alpine-${ref_tag}" gitlab/gitlab-runner:alpine
tag_latest "gitlab/gitlab-runner:alpine-arm-${ref_tag}" gitlab/gitlab-runner:alpine-arm
tag_latest "gitlab/gitlab-runner:alpine-arm64-${ref_tag}" gitlab/gitlab-runner:alpine-arm64

if [[ -z "${PUBLISH_IMAGES}" ]] || [[ "${PUBLISH_IMAGES}" != "true" ]]; then
    echo "Skipping images pushing"
    exit 0
fi

if [[ -n "${CI_REGISTRY}" ]] && [[ -n "${CI_REGISTRY_IMAGE}" ]]; then
    tag "gitlab/gitlab-runner:ubuntu-${ref_tag}" "${CI_REGISTRY_IMAGE}:ubuntu-${ref_tag}"
    tag "gitlab/gitlab-runner:ubuntu-arm-${ref_tag}" "${CI_REGISTRY_IMAGE}:ubuntu-arm-${ref_tag}"
    tag "gitlab/gitlab-runner:ubuntu-arm64-${ref_tag}" "${CI_REGISTRY_IMAGE}:ubuntu-arm64-${ref_tag}"

    tag "gitlab/gitlab-runner:alpine-${ref_tag}" "${CI_REGISTRY_IMAGE}:alpine-${ref_tag}"
    tag "gitlab/gitlab-runner:alpine-arm-${ref_tag}" "${CI_REGISTRY_IMAGE}:alpine-arm-${ref_tag}"
    tag "gitlab/gitlab-runner:alpine-arm64-${ref_tag}" "${CI_REGISTRY_IMAGE}:alpine-arm64-${ref_tag}"

    tag "gitlab/gitlab-runner:${ref_tag}" "${CI_REGISTRY_IMAGE}:${ref_tag}"
    tag "gitlab/gitlab-runner:arm-${ref_tag}" "${CI_REGISTRY_IMAGE}:arm-${ref_tag}"
    tag "gitlab/gitlab-runner:arm64-${ref_tag}" "${CI_REGISTRY_IMAGE}:arm64-${ref_tag}"

    tag_latest gitlab/gitlab-runner:latest "${CI_REGISTRY_IMAGE}:latest"
    tag_latest gitlab/gitlab-runner:arm "${CI_REGISTRY_IMAGE}:arm"
    tag_latest gitlab/gitlab-runner:arm64 "${CI_REGISTRY_IMAGE}:arm64"

    tag_latest gitlab/gitlab-runner:ubuntu "${CI_REGISTRY_IMAGE}:ubuntu"
    tag_latest gitlab/gitlab-runner:ubuntu-arm "${CI_REGISTRY_IMAGE}:ubuntu-arm"
    tag_latest gitlab/gitlab-runner:ubuntu-arm64 "${CI_REGISTRY_IMAGE}:ubuntu-arm64"

    tag_latest gitlab/gitlab-runner:alpine "${CI_REGISTRY_IMAGE}:alpine"
    tag_latest gitlab/gitlab-runner:alpine-arm "${CI_REGISTRY_IMAGE}:alpine-arm"
    tag_latest gitlab/gitlab-runner:alpine-arm64 "${CI_REGISTRY_IMAGE}:alpine-arm64"

    if [[ -n "${CI_REGISTRY_USER}" ]] && [[ -n "${CI_REGISTRY_PASSWORD}" ]]; then
        login "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

        push "${CI_REGISTRY_IMAGE}:ubuntu-${ref_tag}"
        push "${CI_REGISTRY_IMAGE}:ubuntu-arm-${ref_tag}"
        push "${CI_REGISTRY_IMAGE}:ubuntu-arm64-${ref_tag}"

        push "${CI_REGISTRY_IMAGE}:alpine-${ref_tag}"
        push "${CI_REGISTRY_IMAGE}:alpine-arm-${ref_tag}"
        push "${CI_REGISTRY_IMAGE}:alpine-arm64-${ref_tag}"

        push "${CI_REGISTRY_IMAGE}:${ref_tag}"
        push "${CI_REGISTRY_IMAGE}:arm-${ref_tag}"
        push "${CI_REGISTRY_IMAGE}:arm64-${ref_tag}"

        push_latest "${CI_REGISTRY_IMAGE}:latest"
        push_latest "${CI_REGISTRY_IMAGE}:arm"
        push_latest "${CI_REGISTRY_IMAGE}:arm64"

        push_latest "${CI_REGISTRY_IMAGE}:ubuntu"
        push_latest "${CI_REGISTRY_IMAGE}:ubuntu-arm"
        push_latest "${CI_REGISTRY_IMAGE}:ubuntu-arm64"

        push_latest "${CI_REGISTRY_IMAGE}:alpine"
        push_latest "${CI_REGISTRY_IMAGE}:alpine-arm"
        push_latest "${CI_REGISTRY_IMAGE}:alpine-arm64"

        logout "${CI_REGISTRY}"
    fi
fi

if [[ -z "${PUSH_TO_DOCKER_HUB}" ]] || [[ "${PUSH_TO_DOCKER_HUB}" != "true" ]]; then
    echo "Skipping push to Docker Hub"
    exit 0
fi

if [[ -n "${DOCKER_HUB_USER}" ]] && [[ -n "${DOCKER_HUB_PASSWORD}" ]]; then
    login "${DOCKER_HUB_USER}" "${DOCKER_HUB_PASSWORD}"

    push "gitlab/gitlab-runner:ubuntu-${ref_tag}"
    push "gitlab/gitlab-runner:alpine-${ref_tag}"
    push "gitlab/gitlab-runner:arm-${ref_tag}"
    push "gitlab/gitlab-runner:arm64-${ref_tag}"
    push "gitlab/gitlab-runner:${ref_tag}"

    push_latest gitlab/gitlab-runner:ubuntu
    push_latest gitlab/gitlab-runner:latest
    push_latest gitlab/gitlab-runner:alpine
    push_latest gitlab/gitlab-runner:arm
    push_latest gitlab/gitlab-runner:arm64

    release_docker_helper_images

    logout
fi
