#!/usr/bin/env bash

set -eox pipefail

export ARTIFACTS_DEST=artifacts
curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

./artifacts upload \
  --permissions public-read \
  --working-dir "${TARGET_DIR}" \
  --target-paths "${S3_UPLOAD_PATH}/" \
  --max-size "$(du -bs "${TARGET_DIR}" | cut -f1)" \
  $(
    cd "${TARGET_DIR}"
    find . -type f
  )
@echo "\n\033[1m==> Download index file: \033[36mhttps://${ARTIFACTS_S3_BUCKET}.s3.amazonaws.com/${S3_UPLOAD_PATH}/index.html\033[0m\n"
