// Code generated by mockery v1.0.0. DO NOT EDIT.

// This comment works around https://github.com/vektra/mockery/issues/155

package debug

import mock "github.com/stretchr/testify/mock"
import net "net"

// mockHttpServer is an autogenerated mock type for the httpServer type
type mockHttpServer struct {
	mock.Mock
}

// Serve provides a mock function with given fields: listener
func (_m *mockHttpServer) Serve(listener net.Listener) error {
	ret := _m.Called(listener)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.Listener) error); ok {
		r0 = rf(listener)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
