// Code generated by mockery v1.0.0. DO NOT EDIT.

// This comment works around https://github.com/vektra/mockery/issues/155

package debug

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// mockServeMux is an autogenerated mock type for the serveMux type
type mockServeMux struct {
	mock.Mock
}

// Handle provides a mock function with given fields: pattern, handler
func (_m *mockServeMux) Handle(pattern string, handler http.Handler) {
	_m.Called(pattern, handler)
}

// HandleFunc provides a mock function with given fields: pattern, handler
func (_m *mockServeMux) HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request)) {
	_m.Called(pattern, handler)
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *mockServeMux) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}
