#!/bin/bash

set -xe

LXC_NAME="generic-lxc-$GENERIC_ENV_CI_CONCURRENT_ID"

trap 'lxc-stop -k -n "$LXC_NAME"' INT

lxc-attach --clear-env -n "$LXC_NAME" -- /bin/sh -c "/bin/cat > /script-to-run && chmod +x /script-to-run" < "$1"
lxc-attach --clear-env -n "$LXC_NAME" -- "/script-to-run"
